apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Data-Space-Core/management-ui.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: management-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
