apiVersion: v1
kind: ConfigMap
metadata:
  name: route-management-ui-config
  namespace: route-management-ui
data:
  DJANGO_ALLOWED_HOSTS: tenant-a.dil.collab-cloud.eu
  DJANGO_CSRF_TRUSTED_ORIGINS: https://tenant-a.dil.collab-cloud.eu
  KEYCLOAK_BASE_URL: https://dil.collab-cloud.eu/auth
  KEYCLOAK_REALM: tenant-a
  KEYCLOAK_CLIENT_ID: route-management-ui
  KEYCLOAK_SCOPE: openid profile email
  SITE_URL: https://tenant-a.dil.collab-cloud.eu/route
  MANAGEMENT_API_BASE_URL: https://dil.collab-cloud.eu/management
